# Introdução

Nesta seção deve ficar a explicação do tema e das hipóteses, assim como o contexto que levou a sua escolha.

Em algumas disciplinas do curso de Ciência da Computação da Universidade Federal de Campina Grande (UFCG), os alunos são estimulados muitas vezes ao desenvolvimento de várias atividades em grupo. Essas atividades de alguma forma preparam os alunos para o meio profissional da área de computação, visto que a atividade de desenvolvimento de software geralmente é realizada por um grupo de pessoas. Nessas atividades em grupos, a geração de algum tipo de conflito é comum, devido a grande diversidade de pessoas com diferentes personalidades trabalhar juntos, tomar decisões e conciliar difernetes visões dos objetivos do projetos, a geração de conflitos torna-se inevitável. Em razão disso, esse survey tem como objetivo estudar os tipos de conflitos e as formas de gerenciamento mais comuns encontradas por alunos do curso de Ciência da Computação.

As hipóteses a serem testadas a partir do survey são:

* Conflitos decorrentes de desacordo sobre as tarefas são os mais frequentes.
* Conflitos decorrentes de relacionamentos entre os membros da equipe são os que têm maior impacto negativo no projeto.
* Modos de gerenciamento que seguem abordagens colaborativas afetam positivamente o projeto. 
* Modos de gerenciamento que ignoram ou propõem soluções autoritárias para os conflitos afetam negativamente o projeto.

Essas hipóteses baseiam-se nos tipos de conflitos e formas de gerenciamento de conflitos encontrados na literatura, como também os que foram enfrentados utilizados pelos membros desse estudo.